play with test

diff --git a/.gitlab-ci.yml b/.gitlab-ci.yml
--- a/.gitlab-ci.yml
+++ b/.gitlab-ci.yml
@@ -52,3 +52,24 @@ test-check-11:
   stage: "test"
   services:
     - postgres:11
+
+run-tests-from-dir:
+  extends: ".test-check"
+  stage: "test"
+  script: |
+    errcount=0
+    printTail="                                                                      "
+    for f in tests/*.sh; do
+      printf "$f${printTail:0:-${#f}}"
+      bash "$f" -H
+      status=$?
+      if [ "$status" -ne 0 ]; then
+        errcount="$(($errcount+1))"
+      fi
+    done
+    if [ "$errcount" -ne 0 ]; then
+      >&2 echo "Oh no! $errcount tests failed"
+      exit 1
+    fi
+
+
