Apply suggestion to checkup

diff --git a/checkup b/checkup
--- a/checkup
+++ b/checkup
@@ -377,7 +377,7 @@ validate_args() {
     wkhtmltopdf_required_ver="0.12.4"
 
     if [ "$(printf '%s\n' "$wkhtmltopdf_required_ver" "$wkhtmltopdf_current_ver" | sort -V | head -n1)" != "$wkhtmltopdf_required_ver" ]; then 
-      echo "[$(date +'%Y-%m-%dT%H:%M:%S%z')] ERROR: 'wkhtmltopdf' is out-of-date. Update to $wkhtmltopdf_required_ver. See README. Cannot generate PDF." >&2
+      echo "[$(date +'%Y-%m-%dT%H:%M:%S%z')] ERROR: 'wkhtmltopdf' version is outdated. Update to $wkhtmltopdf_required_ver or newer. See README. Cannot generate PDF." >&2
       exit 1
     fi
   fi
