#85 add binary dependency checker. First deps: timeout, awk (gawk)

diff --git a/check b/check
--- a/check
+++ b/check
@@ -542,6 +542,62 @@ is_in_recovery() {
 }
 
 #######################################
+# Check binary dependencies
+# Globals:
+#   KERNEL_NAME, OS_NAME
+# Arguments:
+#   None
+# Returns:
+#   (text) stdtout/stderror
+#######################################
+check_bin_deps() {
+  # detect OS
+  export KERNEL_NAME=$(uname)
+  if [[ "${KERNEL_NAME}" =~ "Darwin" ]]; then
+    export OS_NAME="macOS"
+    dbg "This is macOS"
+  elif [[ "${KERNEL_NAME}" =~ "Linux" ]]; then
+    export OS_NAME="Linux"
+    dbg "This is Linux"
+  else
+    export OS_NAME="Unknown"
+    dbg "Can't detect OS name"
+  fi
+
+  ###### Checking the existence of commands #####
+
+  # timeout
+  if ! $(which gtimeout >/dev/null 2>&1) && ! $(which timeout >/dev/null 2>&1); then
+    err "Can't find the 'timeout' program. Please install it:"
+    if [[ "${KERNEL_NAME}" = "Darwin" ]]; then
+      err "${OS_NAME}: 'brew install coreutils'"
+    elif [[ "${KERNEL_NAME}" = "Linux" ]]; then
+      err "Ubuntu or Debian GNU/${OS_NAME}: 'apt-get install coreutils'"
+    fi
+    return 2
+  else
+    # redefine command (alias won't work inside the script)
+    if [[ "${KERNEL_NAME}" = "Darwin" ]]; then
+      timeout() {
+        gtimeout "$@"
+      }
+    fi
+  fi
+
+  # awk
+  if ! $(which awk >/dev/null 2>&1); then
+    err "Can't find the 'awk' program. Please install it:"
+    if [[ "${KERNEL_NAME}" = "Darwin" ]]; then
+      err "${OS_NAME}: 'brew install gawk'"
+    elif [[ "${KERNEL_NAME}" = "Linux" ]]; then
+      err "Ubuntu or Debian GNU/${OS_NAME}: 'apt-get install gawk'"
+    fi
+    return 2
+  fi
+
+}
+
+#######################################
 # Check rights, set global variables, etc.
 # Globals:
 #   HOST, CHECK_HOST_CMD
@@ -782,6 +838,7 @@ main() {
   export LC_ALL=C
   read_possible_args
   process_cli_args "$@"
+  check_bin_deps
   validate_args
   host_pre_start_checks
   run_checks
