get all .md reports at once (#115)
* generate reports with pghrep

* add binary dependency checker. First deps: timeout, awk, jq

* add golang version check

* cosmetical fixes, renamed internal alias from 'db' to 'node'

diff --git a/check b/check
--- a/check
+++ b/check
@@ -451,9 +451,9 @@ usage() {
 #######################################
 # Generate json report
 # Globals:
-#   CURRENT_CHECK, SCRIPT_DIR, PROJECT,
-#   HOST, JSON_REPORT_DIR, TIMESTAMP_DIR,
-#   TIMESTAMPTZ
+#   CURRENT_CHECK_FNAME, SCRIPT_DIR, PROJECT,
+#   HOST, JSON_REPORTS_DIR, TIMESTAMP_DIR,
+#   TIMESTAMPTZ, MD_REPORTS_DIR
 # Arguments:
 #   input, check_id
 # Returns:
@@ -476,7 +476,7 @@ generate_report_json() {
   echo "$input_json" > "$tmp_input_json_fname"
 
   # final report file name
-  local json_output_fname="${JSON_REPORT_DIR}/${check_id}_${check_name}.json"
+  local json_output_fname="${JSON_REPORTS_DIR}/${check_id}_${check_name}.json"
 
   # use template or existing file
   if [[ -f "$json_output_fname" ]]; then
@@ -485,7 +485,7 @@ generate_report_json() {
     local json_input_fname="${template_fname}"
   fi
 
-  local tmp_output_json_fname=$(mktemp "${JSON_REPORT_DIR}"/${check_id}_${check_name}_tmp_XXXXXX)
+  local tmp_output_json_fname=$(mktemp "${JSON_REPORTS_DIR}"/${check_id}_${check_name}_tmp_XXXXXX)
   jq --argfile Results "${tmp_input_json_fname}" \
      --arg CheckId "${check_id}" \
      --arg CheckName "${check_name}" \
@@ -499,7 +499,7 @@ generate_report_json() {
   rm "$tmp_input_json_fname"
 
   # extend check for current host with actual 'nodes.json' inside a json report
-  tmp_output_json_fname=$(mktemp "${JSON_REPORT_DIR}"/${check_id}_${check_name}_tmp_ex_XXXXXX)
+  tmp_output_json_fname=$(mktemp "${JSON_REPORTS_DIR}"/${check_id}_${check_name}_tmp_ex_XXXXXX)
   jq --argfile nodes_json "${PROJECT_DIR}/nodes.json" \
      '.results.'\"${NATIVE_HOSTNAME}\"'."nodes.json" = $nodes_json' \
      "${json_output_fname}" \
@@ -507,7 +507,7 @@ generate_report_json() {
   mv "$tmp_output_json_fname" "${json_output_fname}"
 
   # update json report by attaching 'nodes.json' into top of the report
-  tmp_output_json_fname=$(mktemp "${JSON_REPORT_DIR}"/${check_id}_${check_name}_tmp_ex_XXXXXX)
+  tmp_output_json_fname=$(mktemp "${JSON_REPORTS_DIR}"/${check_id}_${check_name}_tmp_ex_XXXXXX)
   jq --argfile nodes_json "${PROJECT_DIR}/nodes.json" \
      '.last_nodes_json = $nodes_json' \
      "${json_output_fname}" \
@@ -542,6 +542,138 @@ is_in_recovery() {
 }
 
 #######################################
+# Build pghrep - a .md report generator
+# Globals:
+#   PGHREP_BIN
+# Arguments:
+#   None
+# Returns:
+#   (text) stdtout/stderror
+#######################################
+build_pghrep() {
+  dbg "building pghrep..."
+  local save_pwd="${PWD}"
+  cd "${SCRIPT_DIR}/pghrep"
+  make buildplugins main >/dev/null
+  cd "${save_pwd}"
+  export PGHREP_BIN="${SCRIPT_DIR}/pghrep/bin/pghrep"
+  dbg "done building pghrep"
+}
+
+#######################################
+# Check binary dependencies
+# Globals:
+#   KERNEL_NAME, OS_NAME, timeout()
+# Arguments:
+#   None
+# Returns:
+#   (text) stdtout/stderror
+#######################################
+check_bin_deps() {
+  # detect OS
+  export KERNEL_NAME=$(uname)
+  if [[ "${KERNEL_NAME}" =~ "Darwin" ]]; then
+    export OS_NAME="macOS"
+    dbg "This is macOS"
+  elif [[ "${KERNEL_NAME}" =~ "Linux" ]]; then
+    export OS_NAME="Linux"
+    dbg "This is Linux"
+  else
+    export OS_NAME="Unknown"
+    dbg "Can't detect OS name"
+  fi
+
+  ###### Checking the existence of commands #####
+
+  # timeout
+  if ! $(which gtimeout >/dev/null 2>&1) && ! $(which timeout >/dev/null 2>&1); then
+    err "Can't find the 'timeout' executable. Please install it:"
+    if [[ "${KERNEL_NAME}" = "Darwin" ]]; then
+      err "${OS_NAME}: 'brew install coreutils'"
+    elif [[ "${KERNEL_NAME}" = "Linux" ]]; then
+      err "Debian/Ubuntu GNU/${OS_NAME}: 'sudo apt-get install coreutils'"
+      err "RHEL/CentOS GNU/${OS_NAME}: 'sudo yum install coreutils'"
+    fi
+    return 1
+  else
+    # redefine command (alias won't work inside the script)
+    if [[ "${KERNEL_NAME}" = "Darwin" ]]; then
+      timeout() {
+        gtimeout "$@"
+      }
+    fi
+  fi
+
+  # awk
+  if ! $(which awk >/dev/null 2>&1); then
+    err "Can't find the 'awk' executable. Please install it:"
+    if [[ "${KERNEL_NAME}" = "Darwin" ]]; then
+      err "${OS_NAME}: 'brew install gawk'"
+    elif [[ "${KERNEL_NAME}" = "Linux" ]]; then
+      err "Debian/Ubuntu GNU/${OS_NAME}: 'sudo apt-get install gawk'"
+      err "RHEL/CentOS GNU/${OS_NAME}: 'sudo yum install gawk'"
+    fi
+    return 1
+  fi
+
+  # golang
+  if ! $(which go >/dev/null 2>&1); then
+    err "Can't find the 'go' executable. Please install it:"
+    if [[ "${KERNEL_NAME}" = "Darwin" ]]; then
+      err "${OS_NAME}: 'brew install golang'"
+    elif [[ "${KERNEL_NAME}" = "Linux" ]]; then
+      err "Debian/Ubuntu GNU/${OS_NAME}: 'sudo apt-get install golang'"
+      err "RHEL/CentOS GNU/${OS_NAME}: 'sudo yum install golang'"
+    fi
+    return 1
+  fi
+  # go version check (>= 1.8)
+  re="go([0-9]+.[0-9]+).+"
+  local go_version_full=$(go version)
+  local version="" # short form (e.g. '1.11')
+  local go_version_num="" # get only first two numbers devided by '.'
+  if [[ "${go_version_full}" =~ $re ]]; then
+    version="${BASH_REMATCH[1]}"
+    local major=${version%.*}
+    local minor=${version#*.}
+    go_version_num="${major}${minor}"
+    if [[ $(( go_version_num % 1000 )) -lt "18" ]]; then
+      err "Unsupported golang version '${go_version_full}'"
+      err "Please install golang version >= '1.8'"
+      return 1
+    fi
+  fi
+
+  # jq
+  if ! $(which jq >/dev/null 2>&1); then
+    err "Can't find the 'jq' executable. Please install it:"
+    if [[ "${KERNEL_NAME}" = "Darwin" ]]; then
+      err "${OS_NAME}: 'brew install jq'"
+    elif [[ "${KERNEL_NAME}" = "Linux" ]]; then
+      err "Debian/Ubuntu GNU/${OS_NAME}: 'sudo apt-get install jq'"
+      err "RHEL/CentOS GNU/${OS_NAME}: 'sudo yum install jq'"
+    fi
+    return 1
+  fi
+  # jq version
+  re="jq([0-9]+.[0-9]+).+"
+  local jq_version_full=$(jq --version)
+  local version="" # short form (e.g. '1.11')
+  local jq_version_num="" # get only first two numbers devided by '.'
+  if [[ "${jq_version_full}" =~ $re ]]; then
+    version="${BASH_REMATCH[1]}"
+    local major=${version%.*}
+    local minor=${version#*.}
+    jq_version_num="${major}${minor}"
+    if [[ $(( go_version_num % 1000 )) -lt "15" ]]; then
+      err "Unsupported jq version '${jq_version_full}'"
+      err "Please install jq version >= '1.5'"
+      return 1
+    fi
+  fi
+}
+
+#######################################
 # Check rights, set global variables, etc.
 # Globals:
 #   HOST, CHECK_HOST_CMD
@@ -567,8 +699,9 @@ host_pre_start_checks() {
 # Start/update 'epoch' of the check
 # Globals:
 #   PROJECT_DIR, HOST, NATIVE_HOSTNAME,
-#   ALIAS_NAME, ALIAS_INDEX, ROLE, JSON_REPORT_DIR
-#   TIMESTAMP_DIR, TIMESTAMPTZ, SHORT_DIR
+#   ALIAS_NAME, ALIAS_INDEX, ROLE, JSON_REPORTS_DIR
+#   TIMESTAMP_DIR, TIMESTAMPTZ, SHORT_DIR,
+#   MD_REPORTS_DIR
 # Arguments:
 #   None
 # Returns:
@@ -593,11 +726,12 @@ update_nodes_json() {
 
   # if file does not exist generate alias for a first host
   if [[ ! -f "${PROJECT_DIR}/nodes.json" ]]; then
-    ALIAS_NAME="db1"
+    ALIAS_NAME="node1"
     ALIAS_INDEX="1"
     EPOCH="1"
     prev_role="${ROLE}"
-    JSON_REPORT_DIR="${PROJECT_DIR}/${EPOCH}_${TIMESTAMP_DIR}"
+    JSON_REPORTS_DIR="${PROJECT_DIR}/json_reports/${EPOCH}_${TIMESTAMP_DIR}"
+    MD_REPORTS_DIR="${PROJECT_DIR}/md_reports/${EPOCH}_${TIMESTAMP_DIR}"
     SHORT_DIR="${EPOCH}_${TIMESTAMP_DIR}"
 
     local input_json_fname="${SCRIPT_DIR}/resources/templates/nodes.json"
@@ -615,13 +749,14 @@ update_nodes_json() {
     prev_role=$(jq -r '.hosts.'\"${NATIVE_HOSTNAME}\"'.role' "${PROJECT_DIR}/nodes.json")
     prev_epoch=$(jq -r '.last_check.epoch' "${PROJECT_DIR}/nodes.json")
     prev_dir=$(jq -r '.last_check.dir' "${PROJECT_DIR}/nodes.json")
-    JSON_REPORT_DIR="${PROJECT_DIR}/${prev_dir}"
+    JSON_REPORTS_DIR="${PROJECT_DIR}/json_reports/${prev_dir}"
+    MD_REPORTS_DIR="${PROJECT_DIR}/md_reports/${prev_dir}"
     SHORT_DIR="${prev_dir}"
 
     # exit with error if epoch is not given and this is not first run
     if [[ "${EPOCH}" = "None" ]]; then
       err "epoch not given but epoch '${prev_epoch}' already exist"
-      err "due to avoid overwriting, please choise health-check epoch"
+      err "to avoid overwriting, please choise health-check epoch"
       err "example: ' ./${SCRIPT_NAME} ${ALL_ARGS} -e %NUMBER% '"
       exit 1
     fi
@@ -629,7 +764,7 @@ update_nodes_json() {
     local input_json_fname="${PROJECT_DIR}/nodes.json"
   fi
 
-  export JSON_REPORT_DIR SHORT_DIR
+  export JSON_REPORTS_DIR MD_REPORTS_DIR SHORT_DIR
 
   local role_changed_at="never"
   if [[ "${prev_role}" != "${ROLE}" ]] && [[ "$prev_role" != "null" ]]; then
@@ -643,12 +778,10 @@ update_nodes_json() {
     # get maximum index
     local prev_index=$(jq -r '["\(.hosts | to_entries[] | .value | .index)"] | max' "${PROJECT_DIR}/nodes.json")
     local new_alias_index=$(( prev_index + 1 ))
-    local new_alias_name="db${new_alias_index}"
+    local new_alias_name="node${new_alias_index}"
     ALIAS_INDEX="${new_alias_index}"
     ALIAS_NAME="${new_alias_name}"
   fi
-
-  #TODO(vyagofarov): insert last_check_epoch into each hostname of nodes.json
 
   export ALIAS_NAME ALIAS_INDEX ROLE EPOCH
   dbg "NATIVE_HOSTNAME: '$NATIVE_HOSTNAME'"
@@ -656,14 +789,14 @@ update_nodes_json() {
   dbg "ALIAS_INDEX: '$ALIAS_INDEX'"
   dbg "ROLE: '$ROLE'"
 
-  mkdir -p "${JSON_REPORT_DIR}"
+  mkdir -p "${JSON_REPORTS_DIR}"
 
   # error if two dir names like '${EPOCH}_*' exist
   local cur_epochs_count="0"
-  cur_epochs_count=$(find "${PROJECT_DIR}" -type d -name "${EPOCH}_*" | wc -l)
+  cur_epochs_count=$(find "${JSON_REPORTS_DIR}" -type d -name "${EPOCH}_*" | wc -l)
   if [[ "$cur_epochs_count" -ge "2" ]]; then
     err "more then one directories witn name '${EPOCH}_*' exist:"
-    find "${PROJECT_DIR}" -type d -name "${EPOCH}_*" || true
+    find "${JSON_REPORTS_DIR}" -type d -name "${EPOCH}_*" >&2 || true
     exit 1
   fi
 
@@ -688,8 +821,8 @@ update_nodes_json() {
 # Perform checks
 # All checks must return valid json into stdout
 # Globals:
-#   CURRENT_CHECK, SCRIPT_DIR, HOST, PROJECT_DIR,
-#   NATIVE_HOSTNAME
+#   CURRENT_CHECK_FNAME, SCRIPT_DIR, HOST, PROJECT_DIR,
+#   NATIVE_HOSTNAME, PGHREP_BIN
 #   and all exported internal globals
 # Arguments:
 #   None
@@ -706,15 +839,17 @@ run_checks() {
   fi
   export NATIVE_HOSTNAME
 
+  local pghrep_failed_jsons_stack=""
+
   # perform all checks from './resources/checks/' directory
   msg
   msg "########## Perform checks for host '${NATIVE_HOSTNAME}':"
   local output
-  for CURRENT_CHECK in "${SCRIPT_DIR}"/resources/checks/*_*.sh; do
-    [[ -e "$CURRENT_CHECK" ]] || continue
+  for CURRENT_CHECK_FNAME in "${SCRIPT_DIR}"/resources/checks/*_*.sh; do
+    [[ -e "${CURRENT_CHECK_FNAME}" ]] || continue
     msg
     msg "========== Perform check: =========="
-    msg "$CURRENT_CHECK"
+    msg "$CURRENT_CHECK_FNAME"
 
     local check_is_failed=false
 
@@ -723,12 +858,12 @@ run_checks() {
     export TIMESTAMPTZ=$(date +'%Y-%m-%d %H:%M:%S.0%z')
 
     # perform a check from file
-    output=$(set -euo pipefail ; source "$CURRENT_CHECK") || check_is_failed="true"
+    output=$(set -euo pipefail ; source "$CURRENT_CHECK_FNAME") || check_is_failed="true"
 
     dbg "is check failed?: $check_is_failed"
     msg "========== End of check ==========="
     # extract checkId from check script path
-    local check_path_name="$CURRENT_CHECK"
+    local check_path_name="$CURRENT_CHECK_FNAME"
     local check_id_tmp_a=${check_path_name%%_*.sh}
     local check_id="${check_id_tmp_a##*/}"
 
@@ -751,10 +886,35 @@ run_checks() {
 
     # generate/extend report
     generate_report_json "$output" "$check_id" "$check_name"
+    # generate .md report with help of pghrep (go utility)
+    # ${JSON_REPORTS_DIR}/${check_id}_${check_name}.json
+    mkdir -p "${MD_REPORTS_DIR}"
+    local pghrep_output
+    if ! pghrep_output=$(${PGHREP_BIN} --checkdata="${JSON_REPORTS_DIR}/${check_id}_${check_name}.json" \
+      --outdir="${MD_REPORTS_DIR}" 2>&1) ; then
+      msg "WARNING: ${pghrep_output}"
+      pghrep_failed_jsons_stack="${pghrep_failed_jsons_stack} ${check_id}_${check_name}.json"
+    fi
   done
 
   msg
   msg "All checks has been finished for host '$HOST'!"
+  
+  if ! [[ -z "${pghrep_failed_jsons_stack}" ]]; then
+    msg
+    msg "WARNING: Can't generate md reports for this json's:"
+    local i
+    for i in ${pghrep_failed_jsons_stack}; do
+      echo "        '${i}'"
+    done
+  fi
+
+  msg
+  msg "All .md reports has been saved at directory:"
+  echo "        '${MD_REPORTS_DIR}'"
+
+  msg
+  msg "ALL DONE!"
 }
 
 ######### COMMANDS WRAPPERS ###########
@@ -782,7 +942,9 @@ main() {
   export LC_ALL=C
   read_possible_args
   process_cli_args "$@"
+  check_bin_deps
   validate_args
+  build_pghrep
   host_pre_start_checks
   run_checks
   exit 0
