do not overwrite final report if epoch error occurred

diff --git a/check b/check
--- a/check
+++ b/check
@@ -711,7 +711,15 @@ append_to_final_report() {
 
   local out_fname="${PROJECT_DIR}/${FULL_REPORT_FNAME}"
 
-  # glue
+  # make a header for a FULL_REPORT_FNAME at the first run
+  if [[ ! -f  "${PROJECT_DIR}/${FULL_REPORT_FNAME}" ]]; then
+    echo "# '${PROJECT}' PostgreSQL health check" > "${PROJECT_DIR}/${FULL_REPORT_FNAME}"
+    echo >> "${PROJECT_DIR}/${FULL_REPORT_FNAME}"
+    echo "Started at: " $(date +'%Y-%m-%d %H:%M:%S %z') >> "${PROJECT_DIR}/${FULL_REPORT_FNAME}"
+    echo >> "${PROJECT_DIR}/${FULL_REPORT_FNAME}"
+  fi
+
+  # glue together
   cat "${md_reports_dir}/${report_fname}" >> "${out_fname}"
 }
 
@@ -819,8 +827,9 @@ update_nodes_json() {
 
     # exit with error if epoch is not given and this is not first run
     if [[ "${EPOCH}" = "None" ]]; then
-      echo "${BOLD}ERROR: epoch not given but epoch '${prev_epoch}' already exist${RESET}" >&2
-      echo "to avoid overwriting, please choise health-check epoch" >&2
+      echo "${BOLD}ERROR: epoch not given but directory already exist:${RESET}" >&2
+      echo "    ${JSON_REPORTS_DIR}" >&2
+      echo "to avoid overwriting results of epoch '${BOLD}${prev_epoch}${RESET}', please choice health check epoch with help of option '-e'" >&2
       echo "example:" >&2
       echo "./${SCRIPT_NAME} ${ALL_ARGS} ${BOLD}-e %NUMBER%${RESET}" >&2
       exit 1
@@ -900,12 +909,6 @@ run_checks() {
 
   export PROJECT_DIR="${SCRIPT_DIR}/artifacts/${PROJECT}"
   test -d "${PROJECT_DIR}" || mkdir -p "${PROJECT_DIR}"
-
-  # make a header for a FULL_REPORT_FNAME
-  echo "# '${PROJECT}' PostgreSQL health-check" > "${PROJECT_DIR}/${FULL_REPORT_FNAME}"
-  echo >> "${PROJECT_DIR}/${FULL_REPORT_FNAME}"
-  echo $(date +'%Y-%m-%d %H:%M:%S %z') >> "${PROJECT_DIR}/${FULL_REPORT_FNAME}"
-  echo >> "${PROJECT_DIR}/${FULL_REPORT_FNAME}"
 
   # perform all checks from './resources/checks/' directory
   msg
