posibility to run a single check

diff --git a/check b/check
--- a/check
+++ b/check
@@ -268,6 +268,12 @@ validate_arg_type() {
        err "'$name' = '$value' => is not a '$type' (${re})"
        exit 1
     fi
+  elif [[ $type = "filepath" ]]; then
+    re='.*'
+    if ! [[ $value =~ $re ]]; then
+       err "'$name' = '$value' => is not a '$type' (${re})"
+       exit 1
+    fi
   elif [[ $type = "text" ]]; then
     re='^[a-zA-Z0-9\;\.\s\\\/]+.*'
     if ! [[ $value =~ $re ]]; then
@@ -869,6 +875,14 @@ run_checks() {
   for CURRENT_CHECK_FNAME in "${SCRIPT_DIR}"/resources/checks/*_*.sh; do
     [[ -e "${CURRENT_CHECK_FNAME}" ]] || continue
     msg
+
+    # overwrite all checks to a single check from a file (CLI)
+    if [[ "${FILE}" != "None" ]]; then
+      CURRENT_CHECK_FNAME="${FILE}"
+      if ! [[ -e "${CURRENT_CHECK_FNAME}" ]]; then
+        err "Can't open file: '{CURRENT_CHECK_FNAME}'"
+      fi
+    fi
     msg "========== Perform check: =========="
     msg "$CURRENT_CHECK_FNAME"
 
@@ -915,6 +929,11 @@ run_checks() {
       --outdir="${MD_REPORTS_DIR}" 2>&1) ; then
       msg "WARNING: ${pghrep_output}"
       pghrep_failed_jsons_stack="${pghrep_failed_jsons_stack} ${check_id}_${check_name}.json"
+    fi
+
+    # parse only one file if check is given by CLI
+    if [[ "${FILE}" != "None" ]]; then
+      break
     fi
   done
 
